export const VERSION = 36;
export const RESOURCES = ['alloy', 'ore', 'components', 'food', 'water', 'fuel', 'cells', 'air', 'medicine', 'waste', 'fertilizer', 'keepsakes', 'ice'];
export const BUILDINGS = {
  breaker:{name:'Branch breaker',cost:{alloy:4,components:1},work:8,description:'A two-terminal electrical contact with no side connection. Starts open in manual mode. Optional wet-fault protection latches open when its output branch has a supplied wet cable fault. External bypasses and local batteries can keep a branch powered. Requires habitat floor without cable; open before rotating or changing mode.'},
  waterPipe:{name:'Water pipe / valve',cost:{alloy:1},work:2,overlay:true,description:'A sealed two-unit water pipe with a manual isolation valve. Levels water with adjacent open pipes and reservoirs; stores its own finite contents. Can share tiles with gas pipes and cables. Damage below 50% leaks onto open floor.'},
  waterReservoir:{name:'Water reservoir',cost:{alloy:6,components:1},work:10,description:'Empty passive 32-unit water storage. Connect pipes or a pump; close its valve to retain water. Has no automatic hauler deliveries. Requires a habitat floor.'},
  waterPump:{name:'Directional water pump',cost:{alloy:4,components:1},work:8,demand:3,description:'Uses 3 kW to move up to 0.5 water per tick from the node behind to the node ahead, scaled by condition. Can pump into fuller storage. No passive flow or sideways connection. Requires a habitat floor.'},
  waterIntake:{name:'Water intake',cost:{alloy:4,components:1},work:8,demand:2,description:'Uses 2 kW to move up to 0.5 water per tick from the tile behind into a pipe or reservoir ahead. Select floor pickup, tank input or producer output; promised output remains reserved for haulers. Requires a habitat floor.'},
  waterOutlet:{name:'Water outlet',cost:{alloy:4,components:1},work:8,demand:2,description:'Uses 2 kW to move up to 0.5 water per tick from a node behind into machine input or onto the floor ahead. Respects incoming shipments and recipe demand. Floor discharge can quench fire this tick; wet-wire faults follow next tick. Requires a habitat floor.'},
  gasPipe:{name:'Gas pipe / valve',cost:{alloy:1},work:2,overlay:true,description:'A sealed pipe with a manual isolation valve. Connects adjacent pipes, tanks and vents beneath floors and walls. Stores its own gas; damage below 50% leaks. Use the Gas view to inspect routes.'},
  gasExtractor:{name:'Gas extractor',cost:{alloy:6,components:1},work:10,demand:3,description:'Uses 3 kW to retain room CO2 and smoke in filter mode, or remove the room mixture down to a target pressure in exhaust mode. Moves up to 2 total payload units per tick into a 10-unit chamber; connect pipes and storage. Requires a habitat floor.'},
  gasReservoir:{name:'Gas reservoir',cost:{alloy:6,components:1},work:10,description:'Empty passive 80-unit storage for pipe gas and smoke. No automatic breathing mix delivery. Connect a pump to fill against pressure; close the valve to retain contents. Requires a habitat floor.'},
  gasTank:{name:'Gas supply tank',cost:{alloy:6,components:1},work:10,description:'Haulers deliver breathing mix into a 20-unit loading buffer. Holds up to 80 total gas and smoke units; adjacent pipes connect to its outlet valve. Starts empty. Requires a habitat floor.'},
  gasPump:{name:'Directional gas pump',cost:{alloy:4,components:1},work:8,demand:3,description:'Moves up to two total gas and smoke units per tick from the inlet behind it to the outlet ahead. Rotate in the inspector. Needs adjacent pipes or tanks and 3 kW. No sideways connection or passive flow through a stopped pump.'},
  gasVent:{name:'Regulated gas vent',cost:{alloy:4,components:1},work:8,demand:2,description:'Uses 2 kW to supply its compartment from adjacent gas pipes, stopping at the chosen pressure. Finite supply; cannot recycle CO2. Requires a habitat floor.'},
  waterTank: {name:'Water tank',cost:{alloy:6,components:1},work:10,description:'Haulers fill an eight-unit water buffer. Open the drain valve to release water onto the floor; condition below 50% causes a leak even with the valve closed. Requires a habitat floor.'},
  bilgePump: {name:'Recovery pump',cost:{alloy:6,components:1},work:10,demand:3,description:'Uses 3 kW to collect floor water from its tile and open adjacent tiles. Holds 12 recovered water for hauling. Requires a habitat floor; closed doors block its intake.'},
  reactor: { name:'Compact reactor', cost:{alloy:10,components:2}, work:16, output:40, noise:2, description:'Haulers deliver fuel into a four-unit buffer. Up to 40 kW day or night, with condition-scaled output and waste heat. Adjust output in the inspector. A hot reactor latches off at 120°C; cool below 60°C and reset. Requires a habitat floor.' },
  radiator: { name:'Reactor radiator', cost:{alloy:6,components:1}, work:10, description:'Passive external cooling for an adjacent reactor, or one two tiles away through an intact hull wall. Needs exterior or near-vacuum. Rejects up to 32 heat per tick scaled by condition; no electrical demand.' },
  fence: { name: 'Pasture fence', cost: { alloy: 1 }, work: 3, description: 'Blocks crew and bristlebacks while intact. Tiny tibbles slip through. Does not seal atmosphere. A broken segment leaves a gap; use a latched gate for crew access.' },
  pastureGate: { name: 'Pasture gate', cost: { alloy: 2 }, work: 4, description: 'A latched gate admits crew and their attached animals while keeping loose bristlebacks inside. Hold open for unescorted animal passage. No power or atmosphere seal; a broken gate cannot contain animals.' },
  husbandryPost: { name: 'Husbandry post', cost: { alloy: 4 }, work: 8, description: 'Assign one bristleback. Handlers deliver food and build trust, then collect nutrient curd from a tame, well-fed animal. No power required. Leave nearby lichen for grazing; collected food and manure need hauling.' },
  galley: { name: 'Galley', cost: { alloy: 6, components: 1 }, work: 10, demand: 2, description: 'A cook prepares two unprepared food with 0.25 water in 24 Production work. Quality follows the cook’s Production skill. Keeps ingredient age; prepared food cannot be cooked again. Requires safe air and 5–35 °C.' },
  iceProcessor: { name: 'Ice processor', cost: { alloy: 6, components: 1 }, work: 10, demand: 3, noise: 1, description: 'An operator melts and filters two mined ice into two water with 20 work. Requires a habitat floor, delivered ice and 3 kW of wired power. Water can be hauled into storage or collected through a water intake; consuming machines still need their other ingredients and operator.' },
  artisan: { name: 'Craft workstation', cost: { alloy: 6, components: 1 }, work: 10, demand: 2, noise: 1, description: 'An operator crafts a personal keepsake from two alloy and one component. Style follows the maker’s preference; Production skill determines quality. Needs safe air, 5–40 °C and wired power.' },
  sculpture: { name: 'Alloy sculpture', cost: { alloy: 4 }, work: 10, comfortArt: true, description: 'A hand-built orbital knot on a plinth. Adds art to its compartment; condition matters. Crew who enjoy art benefit most. Repeated sculptures do not stack.' },
  holo: { name: 'Holo display', cost: { alloy: 3, components: 1 }, work: 10, demand: 1, comfortArt: true, description: 'Projects shifting star patterns for room comfort. Requires a component, delivered construction materials and 1 kW of wired power. Damaged displays lose quality; outages switch the art off.' },
  sanitary: { name: 'Sanitary unit', cost: { alloy: 4, components: 1 }, work: 8, description: 'A private dry sanitary facility with an eight-unit sealed waste tank. Crew need safe air and temperature to use it. Haulers empty it into an accepting depot for recycling. No water or power required.' },
  climate: { name: 'Climate unit', cost: { alloy: 6, components: 1 }, work: 10, demand: 2, description: 'Heats or cools its habitat compartment toward a chosen temperature. Needs wired power; damaged equipment has reduced output.' },
  medicalCot: { name: 'Medical cot', cost: { alloy: 4, components: 1 }, work: 8, description: 'A reserved place for treatment and recovery. Needs breathable air, medicine deliveries and a crewmate assigned to medicine.' },
  medlab: { name: 'Medical synthesizer', cost: { alloy: 6, components: 1 }, work: 10, demand: 3, description: 'Turns one food and one water into two medicine with 40 operator work. Requires power and breathable air.' },
  commons: { name: 'Common table', cost: { alloy: 4 }, work: 7, description: 'A place for games and conversation. Put it on a breathable habitat floor; nearby safe tiles become places for faster downtime and stronger social bonds.' },
  cable: { name: 'Power cable', cost: { alloy: 1 }, work: 2, overlay: true, description: 'Connects adjacent cables and equipment terminals. Can run beneath floors, doors and structures. Inspect to isolate, repair or remove it.' },
  floor: { name: 'Habitat floor', cost: { alloy: 1 }, work: 3, description: 'Enclose with hull walls and a door to hold atmosphere.' },
  wall: { name: 'Hull wall', cost: { alloy: 2 }, work: 5, description: 'Seals a room. Blocks movement.' },
  door: { name: 'Pressure door', cost: { alloy: 3 }, work: 5, description: 'Opens briefly for passing crew. Gas flows while open. Can be held open or sealed shut.' },
  bunk: { name: 'Crew bunk', cost: { alloy: 3 }, work: 6, description: 'Crew recover energy here. Place inside a sealed habitat.' },
  solar: { name: 'Solar array', cost: { alloy: 5 }, work: 8, output: 4, description: 'Produces 4 kW in daylight. No fuel consumption.' },
  battery: { name: 'Battery bank', cost: { alloy: 4, components: 1 }, work: 8, description: 'Stores 120 kJ on its own circuit. New banks start empty; charge them from generation or a recovered power cell.' },
  scrubber: { name: 'Life support', cost: { alloy: 5, components: 1 }, work: 9, demand: 3, description: 'Recycles exhaled gas. Delivered breathing mix replaces lost gas and refills the habitat.' },
  atmosphere: { noise: 1, name: 'Atmosphere processor', cost: { alloy: 8, components: 2 }, work: 12, demand: 4, description: 'Crew use water and local volatiles to make breathing mix. Haulers supply life support with its output.' },
  farm: { name: 'Hydroponics', cost: { alloy: 5, components: 1 }, work: 8, demand: 2, description: 'Crew grow two food from one water and 0.25 fertilizer. Needs power, breathable air and 10–35 °C. Recycle waste to replenish nutrients.' },
  recycler: { noise: 1, name: 'Nutrient recycler', cost: { alloy: 6, components: 1 }, work: 10, demand: 2, description: 'Crew process one waste and 0.25 water into 0.25 fertilizer with 25 work. Recovers nutrients from meal waste and spoiled food. Needs wired power; output must be hauled to storage.' },
  refinery: { noise: 1, name: 'Refinery', cost: { alloy: 6 }, work: 9, demand: 3, description: 'Crew refine one ore into two alloy with 20 work. Needs delivered ore and power.' },
  fabricator: { noise: 1, name: 'Parts fabricator', cost: { alloy: 8, components: 2 }, work: 12, demand: 4, description: 'Makes a component from three alloy. Needs a production operator, delivered inputs and power; output must be hauled away.' },
  advanced: { name: 'Advanced array', cost: { alloy: 8, components: 4 }, work: 12, output: 12, description: 'Recovered satellite technology. Produces 12 kW in daylight.' },
  stockpile: { name: 'Cargo depot', cost: { alloy: 2 }, work: 4, description: 'Stores 320 units including reserved supplies. Set accepted resources and hauling priority in the inspector.' },
  trap: { name: 'Biofilter trap', cost: { alloy: 3 }, work: 5, description: 'Captures a tibble within 6 tiles every 10 seconds. Uses a small food lure.' },
};
export const RECIPES = {
  gasTank:{input:{air:10},output:{},duration:1,automatic:true},
  waterTank:{input:{water:4},output:{},duration:1,automatic:true},
  bilgePump:{input:{},output:{water:1},duration:1,automatic:true},
  reactor: { input:{fuel:2}, output:{}, duration:1, automatic:true },
  galley: { input: { food: 2, water: .25 }, output: { food: 2 }, duration: 24, air: 40, temperature: [5,35] },
  iceProcessor: { input: { ice: 2 }, output: { water: 2 }, duration: 20 },
  artisan: { temperature: [5,40], input: {alloy:2,components:1}, output:{keepsakes:1}, duration:30, air:40 },
  medlab: { temperature: [5, 40], input: { food: 1, water: 1 }, output: { medicine: 2 }, duration: 40, air: 40 },
  scrubber: { input: { air: 5 }, output: {}, duration: 1, lifeSupport: true },
  atmosphere: { input: { water: 1 }, output: { air: 10 }, duration: 25 },
  refinery: { input: { ore: 1 }, output: { alloy: 2 }, duration: 20 },
  farm: { temperature: [10, 35], input: { water: 1, fertilizer: .25 }, output: { food: 2 }, duration: 30, air: 40 },
  recycler: { input: { waste: 1, water: .25 }, output: { fertilizer: .25 }, duration: 25 },
  fabricator: { input: { alloy: 3 }, output: { components: 1 }, duration: 45 },
};
export const SPECIES = {
  bristleback: { name: 'Bristleback', description: 'A six-legged frontier grazer. Mineral plates protect a warm, soft abdomen; broad feelers comb lichen from the ground. Its low clicking calls travel through the rock. Paired adults can carry a single brood beneath their plates; hatchlings graze and grow before producing curd.', color: '#a79564' },
  tibble: { name: 'Tibble', description: 'A thumb-sized, translucent seed-mite with three hinged mouthparts. Eats stored food and hydroponic biomass. Well-fed colonies lay clutches quickly. Build a biofilter trap near cargo.', color: '#d8ac91' },
};
export const SITES = {
  surface: { name: 'Kepler’s Rest', label: '01 / SURFACE', sub: 'Basalt frontier · tenuous atmosphere', color: '#cf9066' },
  wreck: { name: 'Relay K-07', label: '02 / NEAR ORBIT', sub: 'Abandoned communications array · vacuum', color: '#78c9c5', fuel: 2, travel: 22 },
  comet: { name: 'The Wayfarer', label: '03 / TRANSIENT', sub: 'Ice and volatiles · limited approach window', color: '#8abedf', fuel: 3, travel: 30 },
  solar: { name: 'Helios Reach', label: '04 / SOLAR SITE', sub: 'Exposed collection platform · radiation hazard', color: '#efb55b', fuel: 4, travel: 38 },
};
export const CREW_NAMES = ['Mara Voss', 'Idris Vale', 'Jun Park', 'Ada Sol', 'Remy Cross', 'Nia Okoye', 'Lev Orlov'];
export const ROLES = ['Commander', 'Engineer', 'Miner', 'Botanist', 'Pilot', 'Medic', 'Technician'];

export const SHUTTLE_FITS = {
  standard: { name: 'Standard hold', capacity: 18, fuel: 0, travel: 0, damage: 1, cost: { alloy: 1 }, description: 'Balanced stock configuration. 18 cargo units.' },
  cargo: { name: 'Expanded cargo racks', capacity: 36, fuel: 1, travel: 6, damage: 1, cost: { alloy: 8, components: 3 }, description: '36 cargo units; one extra fuel per sortie and six extra seconds each way.' },
  shield: { name: 'Storm shelter', capacity: 12, fuel: 1, travel: 0, damage: .25, cost: { alloy: 8, components: 4 }, description: 'Cuts expedition debris and solar injury by 75%; 12 cargo units and one extra fuel per sortie.' },
  drive: { name: 'Transfer drive', capacity: 18, fuel: -1, travel: -6, damage: 1, cost: { alloy: 6, components: 5 }, description: 'One less fuel per sortie and six fewer seconds each way; 18 cargo units.' },
};
