import { expeditionCandidates, selectExpeditionCrew, expeditionLaunchBlock } from './expedition-readiness.js';
import { RESOURCES, SITES, SHUTTLE_FITS } from './data.js';
import { preflightDetails, shipStores } from './preflight-panels.js';
import { quantity } from './inventory.js';
import { inventoryText } from './industry-panels.js';
import { routeTime, routeFuel, reservedCargo } from './expedition.js';
export const missionStatus = m => m.phase === 'boarding' ? 'Team walking back to the shuttle' : m.phase === 'working' ? 'Team on site; haul salvage before recall' : `${m.phase === 'outbound' ? 'Arriving' : 'Returning'} in ${m.remaining}s`;
export function shuttleDetails(s, t) {
  if (t.building !== 'shuttle') return '';
  return `${shipStores(s)}${preflightDetails(s)}<hr><div class="eyebrow">SHUTTLE FITTING</div><p>Installed: ${SHUTTLE_FITS[s.shuttle.fit].name}</p>${!s.flags.salvageReturned ? '<p>Return satellite components to design new fittings.</p>' : ''}${Object.entries(SHUTTLE_FITS).map(([id, fit]) => `<p><strong>${fit.name}</strong><br>${fit.description}</p><button data-action="refit" data-fit="${id}" ${s.mission || s.departure || s.shuttle.fit === id || s.jobs.some(j => j.kind === 'refit') || (id !== 'standard' && !s.flags.salvageReturned) ? 'disabled' : ''}>Install · ${inventoryText(fit.cost)}</button>`).join('')}<p class="crew-hint">Engineers deliver materials to the shuttle. Changing fittings consumes the listed materials; the previous fitting is replaced. Flights wait until work is finished.</p>`;
}
const esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function crewManifest(s,siteId,crewIds){
  const candidates=expeditionCandidates(s),chosen=selectExpeditionCrew(s,crewIds),block=expeditionLaunchBlock(s,siteId),active=s.departure||s.mission;
  if(s.departure?.site===siteId)return '';
  if(active)return `<hr><section data-expedition-manifest><div class="eyebrow">ASSIGNED EXPEDITION TEAM</div><p>${active.crew.map(id=>esc(s.crew.find(c=>c.id===id)?.name||id)).join(' · ')}</p>${active.site!==siteId?`<p>The shuttle is committed to ${esc(SITES[active.site].name)}.</p>`:''}<p class="crew-hint">${s.departure?'Cancel preparation to choose a different team.':'This team remains assigned until the expedition returns.'}</p></section>`;
  return `<hr><section data-expedition-manifest><div class="eyebrow">EXPEDITION TEAM · ${crewIds.length} / 2</div><ol data-expedition-selected>${crewIds.map(id=>{const c=s.crew.find(c=>c.id===id),status=candidates.find(p=>p.id===id);return `<li data-entity="${id}">${esc(c?.name||id)}${status&&!status.eligible?` — ${esc(status.reason)}`:''}</li>`;}).join('')||'<li>No crew selected</li>'}</ol><details data-expedition-roster><summary>Choose two crew</summary><div class="crew-list">${candidates.map(status=>{const c=s.crew.find(c=>c.id===status.id),selected=crewIds.includes(c.id);return `<button class="crew-row" data-action="expedition-crew" data-ui-action="expedition.crew.select" data-crew="${c.id}" data-entity="${c.id}" aria-pressed="${selected}" ${!selected&&(!status.eligible||crewIds.length>=2)?'disabled':''}><span aria-hidden="true">${selected?'☑':'☐'}</span><span class="crew-text"><strong>${esc(c.name)}</strong><small>${esc(c.role)} · Extraction ${c.skills.mining.level}${c.labors.mining?'':' (off)'} · Hauling ${c.skills.hauling.level}${c.labors.hauling?'':' (off)'}</small><small>${esc(status.eligible?c.activity:status.reason)}</small></span></button>`;}).join('')}</div><p class="crew-hint">Uncheck a selected crew member to free a slot. Your choices stay selected if readiness changes. Extraction and hauling duties must be enabled to do those jobs in the field.</p></details>${!chosen.ok?`<p data-expedition-selection-blocked>${esc(chosen.message)}</p>`:''}${block?`<p data-expedition-launch-blocked>${esc(block.message)}</p>`:''}<button data-action="launch" data-crew-ids="${esc(JSON.stringify(crewIds))}" class="primary" ${!chosen.ok||block?'disabled':''}>Prepare selected team →</button></section>`;
}
export function expeditionDetails(s, siteId, crewIds=expeditionCandidates(s).filter(c=>c.eligible).slice(0,2).map(c=>c.id)) {
  const m = s.mission?.site === siteId ? s.mission : null, def = SITES[siteId], fit = SHUTTLE_FITS[m?.fit || s.shuttle.fit];
  const descriptions = { wreck: 'Recover components for industry and shuttle fittings. Debris threatens crews outside the dock.', comet: 'Harvest ice and fuel. Leave enough time to carry cargo and walk back before the approach window closes.', solar: 'Collectors produce charged cells at the platform. Haul them to the dock between solar squalls.' };
  const loose = s.sites[siteId].tiles.reduce((n, t) => n + quantity(t.drop), 0);
  return `<div class="eyebrow">${m ? 'EXPEDITION' : 'FRONTIER OPPORTUNITY'}</div><h2>${def.name}</h2><p>${descriptions[siteId]}</p><dl>
    <dt>Fitting</dt><dd>${fit.name}</dd><dt>Transit each way</dt><dd>${routeTime(s, siteId)}s</dd><dt>Service supplies</dt><dd>${routeFuel(s, siteId)} fuel (both legs) · 2 food · breathing mix for refill and reserve</dd><dt>Hold capacity</dt><dd>${m?.capacity || fit.capacity} units</dd>
    ${siteId === 'solar' ? '<dt>Collector kit</dt><dd>6 alloy · 2 components</dd>' : ''}
    ${siteId === 'comet' ? `<dt>${s.tick < s.comet.arrives ? 'Arrives in' : 'Departs in'}</dt><dd>${Math.max(0, (s.tick < s.comet.arrives ? s.comet.arrives : s.comet.leaves) - s.tick)}s</dd>` : ''}
    ${siteId === 'wreck' ? `<dt>Next debris pass</dt><dd>${65 - s.tick % 65}s</dd>` : ''}
    ${m ? `<dt>Status</dt><dd>${missionStatus(m)}</dd><dt>Loaded cargo</dt><dd>${inventoryText(m.cargo)}</dd><dt>Hold used / claimed</dt><dd>${quantity(m.cargo)} / ${reservedCargo(s)} units</dd><dt>Loose on site</dt><dd>${loose} units</dd>` : ''}</dl>
    ${preflightDetails(s, siteId)}${crewManifest(s,siteId,crewIds)}<div class="eyebrow">CARGO TO COLLECT</div><div class="job-priority expedition-cargo">${RESOURCES.map(r => `<button data-action="cargo-policy" data-resource="${r}" aria-pressed="${s.shuttle.accepted.includes(r)}" class="${s.shuttle.accepted.includes(r) ? 'active' : ''}">${r}</button>`).join('')}</div><p class="crew-hint">Only enabled materials are picked up. Existing carried shipments stay reserved. Uncollected piles persist for another visit; return cargo still needs surface hauling.</p>
    ${m?.phase === 'boarding' ? '<button data-action="resume-expedition">Resume field work</button><p class="crew-hint">Resume work to clear a blocked route. Automatic safety recall still applies.</p>' : ''}${m ? `<button data-action="recall" class="primary" ${['returning', 'boarding'].includes(m.phase) ? 'disabled' : ''}>Return to shuttle & recall →</button>` : ''}`;
}
