import { gasAmount, GASES, roomAt } from './atmosphere.js';
import { GAS_DIRECTIONS, gasNode, gasCapacity, gasPayload, gasPressure, gasStatus } from './gas-networks.js';

const gasNames = { oxygen:'Oxygen', inert:'Inert gas', carbonDioxide:'Carbon dioxide', co2:'Carbon dioxide' };
const directions = { east:'East ↘', south:'South ↙', west:'West ↖', north:'North ↗' };

export function gasDetails(site,t) {
  const node=gasNode(t),device=t.gasDevice;
  if(!node&&!device)return '';
  const status=gasStatus(site,t),condition=t.pipe?t.pipe.hp:t.hp;
  let html=`<hr><section data-gas-panel><div class="eyebrow">GAS NETWORK</div><p data-gas-status>${status.status}</p>`;
  if(node){
    const amount=gasAmount(node.gas);
    html+=`<dl><dt>Stored load</dt><dd data-gas-amount>${gasPayload(t).toFixed(3)} / ${gasCapacity(t)} units</dd><dt>Retained smoke</dt><dd data-gas-smoke>${(node.smoke||0).toFixed(3)} units</dd><dt>Gas pressure</dt><dd data-gas-pressure>${gasPressure(t).toFixed(1)}% nominal</dd><dt>${t.pipe?'Pipe':'Equipment'} condition</dt><dd>${condition.toFixed(1)}%</dd><dt>Port valve</dt><dd>${node.open?'Open':'Closed — ports isolated'}</dd></dl><button data-action="gas-valve" aria-pressed="${node.open}">${node.open?'Close gas valve':'Open gas valve'}</button><details data-gas-composition><summary>Gas mixture</summary><dl>${GASES.map(k=>`<dt>${gasNames[k]||k}</dt><dd>${node.gas[k].toFixed(3)} units${amount?` · ${(node.gas[k]/amount*100).toFixed(1)}%`:''}</dd>`).join('')}</dl><p class="crew-hint">Smoke uses storage capacity alongside gas. Pressure reflects the gas mixture; it excludes smoke.</p></details>`;
  }
  if(t.pipe)html+=`${t.pipe.hp<100?'<button data-action="repairPipe">Repair pipe · 1 alloy</button>':''}<button data-action="removePipe">Dismantle pipe</button><p class="crew-hint">Adjacent pipes, tanks, reservoirs, vents and extractors exchange their contents. Closing the valve isolates this segment from its neighbors; it does not seal damage. Pipes can cross beneath hull walls and coexist with cables. Damage below 50% leaks; dismantling releases the remaining gas and smoke.</p>`;
  if(t.building==='gasTank')html+=`<dl><dt>Delivered breathing mix</dt><dd>${(t.machine.input.air||0).toFixed(2)} / 20 units</dd><dt>Refilling</dt><dd>${t.machine.status}</dd></dl><button data-action="machine" aria-pressed="${t.machine.enabled}">${t.machine.enabled?'Pause gas tank refill':'Enable gas tank refill'}</button><p class="crew-hint">Haulers bring existing breathing mix; new tanks start empty. Up to 2 units per tick enter the tank from its delivered supply. Pausing refill leaves stored gas connected until you close the valve.</p>`;
  if(t.building==='gasReservoir')html+='<p class="crew-hint">This passive reservoir starts empty and holds up to 80 units of gas and smoke. It receives whatever enters its pipe route and needs no power. Close its valve to trap the contents. Dirty gas returned through a supply vent contaminates the room.</p>';
  if(t.building==='gasPump')html+=`<dl><dt>Condition</dt><dd>${condition.toFixed(1)}%</dd><dt>Inlet → outlet</dt><dd>${directions[device.direction]}</dd></dl><div class="job-priority" aria-label="Gas pump outlet direction">${Object.keys(GAS_DIRECTIONS).map(direction=>`<button data-action="gas-direction" data-direction="${direction}" aria-pressed="${direction===device.direction}">${directions[direction]}</button>`).join('')}</div><button data-action="gas-toggle" aria-pressed="${device.enabled}">${device.enabled?'Disable gas pump':'Enable gas pump'}</button><p class="crew-hint">The arrow points toward the outlet. Put an inlet pipe or tank behind the pump and an outlet pipe or vent ahead. Side neighbors do not connect. Wired power moves up to 2 units per tick, scaled by condition.</p>`;
  if(t.building==='gasVent'){
    const room=roomAt(site,t.x,t.y);
    html+=`<dl><dt>Room pressure</dt><dd>${room?`${room.pressure.toFixed(1)}% nominal`:'Outside habitat'}</dd></dl><form class="production-form" data-gas-form><label>Vent target (% nominal)<input name="gas-target" aria-label="Vent target pressure" type="number" required min="0" max="150" step="1" value="${device.target}"></label><button type="submit">Apply vent target</button></form><button data-action="gas-toggle" aria-pressed="${device.enabled}">${device.enabled?'Disable supply vent':'Enable supply vent'}</button><p class="crew-hint">Powered supply releases stored pipe gas into this compartment until its pressure reaches the target. It does not remove excess gas or clean the mixture.</p>`;
  }
  if(t.building==='gasExtractor'){
    const room=roomAt(site,t.x,t.y),filter=device.mode==='filter';
    html+=`<dl><dt>Room pressure</dt><dd>${room?`${room.pressure.toFixed(1)}% nominal`:'Outside habitat'}</dd><dt>Extraction mode</dt><dd>${filter?'Filter CO₂ and smoke':'Exhaust room mixture'}</dd></dl><div class="job-priority" aria-label="Gas extractor mode"><button data-action="gas-extractor-mode" data-mode="filter" aria-pressed="${filter}">Filter</button><button data-action="gas-extractor-mode" data-mode="exhaust" aria-pressed="${!filter}">Exhaust</button></div>${filter?'':`<form class="production-form" data-gas-form data-gas-extractor-form><label>Exhaust target (% nominal)<input name="gas-target" aria-label="Exhaust target pressure" type="number" required min="0" max="150" step="1" value="${device.target}"></label><button type="submit">Apply exhaust target</button></form>`}<button data-action="gas-extractor-toggle" aria-pressed="${device.enabled}">${device.enabled?'Disable gas extractor':'Enable gas extractor'}</button><p class="crew-hint">${filter?'Filter mode takes only carbon dioxide and smoke, leaving oxygen and inert gas in the room.':'Exhaust mode takes the room mixture until gas pressure reaches the target.'} Captured material stays in this device and its connected pipes. Power is required; extraction stops when storage is full. Route the outlet through a pump into a reservoir to keep collecting.</p>`;
  }
  html+='<p class="crew-hint">Supply: tank → pump → pipe → vent. Collection: extractor → pipe → pump → reservoir. Use Gas view to trace routes and Power view to wire powered devices.</p></section>';
  return html;
}
